//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_v3
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.friends = new HashSet<friend>();
            this.historyPaids = new HashSet<historyPaid>();
        }
    
        public int id { get; set; }
        public string FullName { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string IdCard { get; set; }
        public string PhoneNumber { get; set; }
        public string FamilyPhoneNumber { get; set; }
        public int Money { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int InterestId { get; set; }
        public int CategoryId { get; set; }
        public string Note { get; set; }
        public bool Status { get; set; }
        public string Address { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public bool Sex { get; set; }
    
        public virtual category category { get; set; }
        public virtual interestRate interestRate { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual ICollection<friend> friends { get; set; }
        public virtual ICollection<historyPaid> historyPaids { get; set; }
    }
}
